spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-flyway3?autoReconnect=true&useSSL=false&serverTimezone=JST
    username: root
    password: Megane-33
    driver-class-name: com.mysql.jdbc.Driver